### ISSUE TITLE
I can't see any information about how priority works when using multiple webAcl 

### ISSUE THREAD

**Issue by abrarcv170** [awsdocs/aws-waf-and-shield-advanced-developer-guide#14]

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
