### ISSUE TITLE
Bot control 

### ISSUE THREAD

**Issue by alysenok** [awsdocs/aws-waf-and-shield-advanced-developer-guide#17]
Couple questions: 
1. What is criteria for labeling request to the certain bot. Is it by User-Agent or IP, or something else?
2. Why the following rule doesn't work as expected after enabling Bot protection
{
  "Name": "Bot_control_rule",
  "Priority": 10,
  "Action": {
    "Block": {}
  },
  "VisibilityConfig": {
    "SampledRequestsEnabled": true,
    "CloudWatchMetricsEnabled": true,
    "MetricName": "Bot_control_rule"
  },
  "Statement": {
    "AndStatement": {
      "Statements": [
        {
          "LabelMatchStatement": {
            "Scope": "LABEL",
            "Key": "awswaf:managed:aws:bot-control:bot:name:yandexbot"
          }
        },
        {
          "LabelMatchStatement": {
            "Scope": "LABEL",
            "Key": "awswaf:managed:aws:bot-control:bot:name:baidu"
          }
        }
      ]
    }
  }
}
Thank you.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
