### ISSUE TITLE
HELP WANTED: AWS WAF Troubleshooting questions (and answers)

### ISSUE THREAD

**Issue by joeholl** [awsdocs/aws-waf-and-shield-advanced-developer-guide#2]
As much as I'd like to think AWS WAF and the AWS WAF documentation is perfect, I've got to believe that every now and then you might run into problems.

I want to help you fix those problems in our documentation. If you have ideas about any common troubleshooting issues that I should include in our AWS WAF Developer Guide, please let me know! Better yet, tell me about troubleshooting tips and tricks you've used to find and fix problems.

Submit a pull request as explained in these directions: https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/CONTRIBUTING.md .  

I look forward to hearing from you.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
