### ISSUE TITLE
Step 1, part 4 has outdated information

### ISSUE THREAD

**Issue by cihati** [awsdocs/aws-waf-and-shield-advanced-developer-guide#3]
For instance, Request Threshold and WAF Block Period default values

**Comment by joeholl** [comment]
Hi,

Thank you for the feedback. Can you specify the title of the page with the incorrect information?

**Comment by cihati** [comment]
@joeholl  I was talking about this page: https://docs.aws.amazon.com/waf/latest/developerguide/tutorials-ddos-cross-service-WAF.html

Also, it suggests turning off HTTP Flood Protection. "Choose no. The rate-based rules provided by AWS WAF are a more efficient way to set up this protection. After completing this tutorial, if you want to add rate-based rules, you can find more information in How AWS WAF Works." However, I think now the AWS WAF Security Automations template now has rate-based HTTP Flood Protection

**Comment by joeholl** [comment]
Thanks again! These updates have been made and published.
